# Generated by Django 5.0.2 on 2024-03-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaguy',
            name='pass_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='securityguy',
            name='pass_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='QACheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_checkin_id', models.CharField(max_length=100)),
                ('qa_guy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.qaguy')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityCheckins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_checkout_id', models.CharField(max_length=100)),
                ('security_guy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agent.securityguy')),
            ],
        ),
    ]
