# Generated by Django 5.0.2 on 2024-03-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_qaguy_pass_code_alter_securityguy_pass_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecurityCheckins',
            new_name='SecurityCheckin',
        ),
    ]
