# Generated by Django 5.0.2 on 2024-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_securitycheckins_securitycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaguy',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='securityguy',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
