# Generated by Django 4.1.7 on 2024-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('qa_agent', 'QA Agent'), ('checkout_agent', 'Checkout Agent')], default='customer', max_length=20),
        ),
    ]
